services:
  app:
    build: .
    container_name: documind-app
    ports:
      - "8501:8501"
    environment:
      OLLAMA_HOST: http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - chroma_data:/app/chroma_db

  ollama:
    image: ollama/ollama:latest
    container_name: documind-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
  chroma_data: